services:
  neo:
    image: neo4j:5.26.5
    ports:
      - "7474:7474"
      - "7687:7687"
    expose:
      - 7474
      - 7687
    volumes:
      - neobase:/data/neo
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=${NEO4J_ACCEPT}
      - dbms.connector.bolt.listen_address=:7687
      - dbms.connector.bolt.advertised_address=:7687
    networks:
      - net

volumes:
  neobase:
    driver: local

networks:
  net:
    driver: bridge