from book.models.resources.BookResource import BookResource
from book.models.resources.BookNameResource import BookNameResource
from book.models.resources.BookPersonResource import BookPersonResource
from book.models.resources.BookResumeResource import BookResumeResource
from book.models.resources.BookExtraResource import BookExtraResource
from book.models.resources.BookLanguageResource import BookLanguageResource
from book.models.resources.BookCategoryResource import BookCategoryResource
from book.models.resources.BookDepartmentResource import BookDepartmentResource